"""Add first_name and last_name to users

Revision ID: 22931b10a819
Revises: 104d4aad20e0
Create Date: 2023-04-19 17:18:27.439336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22931b10a819'
down_revision = '104d4aad20e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
