"""Add user_id into Article

Revision ID: 248f8f053ae3
Revises: 15b67610105e
Create Date: 2023-04-28 16:26:42.149044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248f8f053ae3'
down_revision = '15b67610105e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
